# Generated by Django 5.1.2 on 2024-10-15 09:07

import appT.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TitanicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('gender', models.CharField(max_length=6, validators=[appT.models.only_string])),
                ('fare', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pclass', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('embarked', models.CharField(max_length=1, validators=[appT.models.only_string])),
                ('cabin', models.CharField(max_length=1, validators=[appT.models.only_string])),
                ('sbsp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('parch', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
